CREATE TABLE `ps_map_data_halflife_firearms` (
  `dataid` int unsigned NOT NULL default '0',
  `red_forcekills` smallint unsigned NOT NULL default '0',
  `blue_forcekills` smallint unsigned NOT NULL default '0',
  `joinedred_force` smallint unsigned NOT NULL default '0',
  `joinedblue_force` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `red_forcewon` smallint unsigned NOT NULL default '0',
  `blue_forcewon` smallint unsigned NOT NULL default '0',
  `red_forcelost` smallint unsigned NOT NULL default '0',
  `blue_forcelost` smallint unsigned NOT NULL default '0',
  `bandage` smallint unsigned NOT NULL default '0',
  `medevac` smallint unsigned NOT NULL default '0',
  `capturepoint` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_data_halflife_firearms` (
  `dataid` int unsigned NOT NULL default '0',
  `red_forcekills` smallint unsigned NOT NULL default '0',
  `blue_forcekills` smallint unsigned NOT NULL default '0',
  `red_forcedeaths` smallint unsigned NOT NULL default '0',
  `blue_forcedeaths` smallint unsigned NOT NULL default '0',
  `joinedred_force` smallint unsigned NOT NULL default '0',
  `joinedblue_force` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `red_forcewon` smallint unsigned NOT NULL default '0',
  `blue_forcewon` smallint unsigned NOT NULL default '0',
  `red_forcelost` smallint unsigned NOT NULL default '0',
  `blue_forcelost` smallint unsigned NOT NULL default '0',
  `bandage` smallint unsigned NOT NULL default '0',
  `medevac` smallint unsigned NOT NULL default '0',
  `capturepoint` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_maps_halflife_firearms` (
  `dataid` int unsigned NOT NULL default '0',
  `red_forcekills` smallint unsigned NOT NULL default '0',
  `blue_forcekills` smallint unsigned NOT NULL default '0',
  `red_forcedeaths` smallint unsigned NOT NULL default '0',
  `blue_forcedeaths` smallint unsigned NOT NULL default '0',
  `joinedred_force` smallint unsigned NOT NULL default '0',
  `joinedblue_force` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `red_forcewon` smallint unsigned NOT NULL default '0',
  `blue_forcewon` smallint unsigned NOT NULL default '0',
  `red_forcelost` smallint unsigned NOT NULL default '0',
  `blue_forcelost` smallint unsigned NOT NULL default '0',
  `bandage` smallint unsigned NOT NULL default '0',
  `medevac` smallint unsigned NOT NULL default '0',
  `capturepoint` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;

-- Moved from defaults.sql.
INSERT INTO `ps_config_events` (`id`, `gametype`, `modtype`, `eventname`, `alias`, `regex`, `idx`, `ignore`, `codefile`) 
    VALUES 
        (1,'halflife','','kill','','/^\"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',10,0,''),
        (2,'halflife','','attacked','','/^\"(.+(?:<[^>]*>))\" attacked \"(.+(?:<[^>]*>))\" with \"([^\"]+)\"(.*)/',20,1,''),
        (3,'halflife','','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered \"([^\"]+)\"(.*)/',30,0,''),
        (4,'halflife','','round','','/^World triggered \"([^\"]+)\"(.*)/',40,0,''),
        (5,'halflife','','entered_game','','/^\"(.+(?:<[^>]*>))\" entered the game(.*)/',50,0,''),
        (6,'halflife','','joined_team','','/^\"(.+(?:<[^>]*>))\" joined team \"([^\"]+)\"/',60,0,''),
        (7,'halflife','','suicide','','/^\"(.+(?:<[^>]*>))\" committed suicide with \"([^\"]+)\"(.*)/',70,0,''),
        (8,'halflife','','changed_name','','/^\"(.+(?:<[^>]*>))\" changed name to \"([^\"]+)\"/',80,0,''),
        (9,'halflife','','connected','','/^\"(.+(?:<[^>]*>))\" connected, address \"([^\"]+)\"/',90,0,''),
        (10,'halflife','','connected_steamid','','/^\"(.+(?:<[^>]*>))\" (?:STEAM|VALVE) USERID (.+)/',100,0,''),
        (11,'halflife','','disconnected','','/^\"(.+(?:<[^>]*>))\" disconnected/',110,0,''),
        (12,'halflife','','chat','','/^\"(.+(?:<[^>]*>))\" say(_team)* \"(.*)\"?(.*)/',120,0,''),
        (13,'halflife','','rcon','','/^(Bad )?Rcon: \"rcon (-*\\d+) \"?(.*?)\"? (.+?)(?:\" from \"([^\"]+)\")?/',130,1,''),
        (14,'halflife','','cheated','','/^Secure: \"(.+(?:<[^>]*>))\" was detected cheating/',140,0,''),
        (15,'halflife','','ban','','/^(Addip|Ban(?:id)?): \"([^\"]+)\" was (?:kicked and )?(?:banned)(?: by IP)? \"([^\"]+)\" by \"([^\"]+)\"(.*)/',150,1,''),
        (16,'halflife','','unban','','/^Remove(id|ip): \"([^\"]+)\" was unbanned by \"(.+(?:<[^>]*>))\"(.*)/',160,1,''),
        (17,'halflife','','kick','','/^Kick: \"(.+(?:<[^>]*>))\" was kicked by \"(.+(?:<[^>]*>)?)\"(.*)/',170,0,''),
        (18,'halflife','','pingkick','','/^\"(.+(?:<[^>]*>))\" kicked due to high ping(.*)/',180,0,''),
        (19,'halflife','','ffkick','','/^\"(.+(?:<[^>]*>))\" has been auto kicked from the game for TKing/',190,0,''),
        (20,'halflife','','startedmap','','/^(Started|Loading) map \"([^\"]+)\"(.*)/',200,0,''),
        (21,'halflife','','logstartend','','/^Log file (started|closed)(.*)/',210,0,''),
        (22,'halflife','','ignored1','','/^[Ss]erver (?:cvars?|say|shutdown)/',220,1,''),
        (23,'halflife','','ignored2','','/^(?:\\]TSC\\[|Succeeded|FATAL|-|Loaded)/',230,1,''),
        (24,'halflife','','ignored3','','/^(?:Config|Swear|server_)/',240,1,''),
        (25,'halflife','','ignored4','','/^\"[^\"]+\" = \"/',250,1,''),
        (33,'halflife','','changed_role','','/^\"(.+(?:<[^>]*>))\" changed role to \"([^\"]+)\"/',330,0,''),
        (45,'halflife','','rcon2','','/^rcon from/',130,1,''),
        (48,'halflife','','spatial','','/^\\[KTRAJ\\] \"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',480,0,''),
        (49,'halflife','','plugin','','/^\\[[^\\]]+\\]/',490,1,''),
        (50,'halflife','','console','','/^(CONSOLE|PLAYER FILTER) :/',500,1,''),
        (60,'halflife','firearms','firearms_ffkill','','/^TEAMKILL: \"(.+(?:<[^>]*>))\" killed team mate \"(.+(?:<[^>]*>))\"!/',600,0,''),
        (100,'halflife','','ignored5','','/^Server name is \"([^"]+)\"/',1000,1,''),
        (101,'halflife','','ignored6','','/^Connection to Steam servers successful./',1010,1,''),
        (102,'halflife','','ignored7','','/^VAC secure mode is activated./',1020,1,''),
        (103,'halflife','','ignored8','','/^Assigned anonymous gameserver Steam ID \[(.:\\d:\\d+:\\d+)\]./',1030,1,''),
        (104,'halflife','','ignored9','','/^Public IP is ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|(\\d{1,3}\.){3}\\d{1,3}./',1040,1,'');

INSERT INTO `ps_config_plrbonuses` (`id`, `eventname`, `enactor`, `enactor_team`, `victim`, `victim_team`, `description`, `gametype`, `modtype`) 
    VALUES 
        (34,'ffkill',-10,0,0,0,'when a player kills a team mate','',''),
        (59,'medevac',2,0,0,0,'A medic called in an medevac on a casualty.','halflife','firearms'),
        (60,'capturepoint',1,0,0,0,'A player captured an objective.','halflife','firearms'),
        (77,'medic_heal',1,0,0,0,'A medic treated a team mate.','halflife','firearms');

INSERT INTO `ps_config_awards` (`id`, `enabled`, `idx`, `type`, `negative`, `class`, `name`, `groupname`, `phrase`, `expr`, `order`, `where`, `limit`, `format`, `gametype`, `modtype`, `rankedonly`, `description`) 
    VALUES 
        (4,1,10,'player',0,'','Highest Skill','','{$player.link} has the highest skill with {$award.value}','{$skill}','desc','',0,'%.02f',NULL,NULL,1,'Player with the highest skill'),
        (6,1,20,'player',0,'','Most Kills','','{$player.link} has killed the most players ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Player with the most kills (any team)'),
        (8,1,70,'player',0,'','Most Time Online','','{$player.link} has been online the longest ({$award.value})','{$onlinetime}','desc','',25,'compacttime',NULL,NULL,1,'Player with the most online time'),
        (9,1,190,'weaponclass',0,'','Most Kills with {$weapon.class} weapons','','{$player.link} has the most {$weapon.class} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with {$weapon.class} type weapons (including: {$weapon.list}).'),
        (10,1,180,'weapon',0,'','Most Kills with {$weapon.name}','','{$player.link} has the most {$weapon.link} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with a {$weapon.name}'),
        (13,1,30,'player',0,'','Most Bonus Points','','{$player.link} achieved the most bonus points ({$award.value})','{$totalbonus}','desc','',25,'commify',NULL,NULL,1,'Player that has achieved the most bonus points.'),
        (22,1,140,'player',0,'','Most Flags Captured','','{$player.link} has captured the most flags ({$award.value})','{$flagscaptured}','desc','',10,'commify','halflife','firearms',1,'Player has captured the most flags.'),
        (23,1,50,'player',1,'','Worst Teammate','','{$player.link} has killed the most teammates ({$award.value})','{$ffkills}','desc','',0,'commify',NULL,NULL,1,'Player with the most friendly fire kills (ie: Worst Teammate)'),
        (25,1,60,'player',1,'','Worst Team Kill Percentage','','{$player.link} has the highest team kill percentage ({$award.value})','{$ffkills} / {$kills} * 100','desc','',0,'%0.02f%%',NULL,NULL,1,'Player with the highest team kill percentage.'),
        (30,1,300,'player',0,'','Most Map Objectives Completed','','{$player.link} has completed the most map objectives ({$award.value}).','{$capturepoint}','desc','',10,'commify','halflife','firearms|tfc',1,'Player who has completed the most map objectives.'),
        (32,1,320,'player',0,'','Most Active Medic','','{$player.link} is the most active medic with {$award.value} medic actions.','{$bandage} + {$medevac}','desc','',10,'commify','halflife','firearms',1,'Player with the most medic actions.');

INSERT INTO `ps_config_overlays` (`id`, `gametype`, `modtype`, `map`, `minx`, `miny`, `maxx`, `maxy`, `width`, `height`, `flipv`, `fliph`, `rotate`) 
    VALUES 
        (74, 'halflife', 'firearms', 'obj_armory', -3705, -1690, 2545, 3840, 600, 536, 1, 0, 0),
        (75, 'halflife', 'firearms', 'obj_bocage', -3325, -3900, 3855, 3900, 549, 600, 1, 0, 0),
        (76, 'halflife', 'firearms', 'obj_paradise', -3590, -3200, 3825, 3960, 600, 580, 1, 0, 0),
        (77, 'halflife', 'firearms', 'obj_sweden', -4040, -1285, 3600, 3560, 600, 378, 1, 0, 0),
        (78, 'halflife', 'firearms', 'obj_thanatos', -3885, -3860, 3445, 3705, 591, 600, 1, 0, 0),
        (79, 'halflife', 'firearms', 'obj_vengeance', -3500, -3925, 3115, 3985, 503, 600, 1, 0, 0),
        (80, 'halflife', 'firearms', 'obj_willow', -2940, -3465, 3970, 2215, 600, 491, 1, 0, 0),
        (81, 'halflife', 'firearms', 'ps_bridge', -3330, -3280, 1630, 3230, 457, 600, 1, 0, 0),
        (82, 'halflife', 'firearms', 'ps_coldwar', -4040, -4015, 2660, 3550, 529, 600, 1, 0, 0),
        (83, 'halflife', 'firearms', 'ps_crash', -2400, -3705, 3700, 3045, 600, 542, 1, 0, 0),
        (84, 'halflife', 'firearms', 'ps_marie', -4035, -3965, 3985, 2015, 600, 450, 1, 0, 0),
        (85, 'halflife', 'firearms', 'ps_river', -3895, -3895, 1590, 3970, 600, 420, 1, 0, 0),
        (86, 'halflife', 'firearms', 'ps_splinter', -3725, -2720, 3830, 3035, 600, 454, 1, 0, 0),
        (87, 'halflife', 'firearms', 'ps_storm_r1', -3950, -1895, 4000, 1890, 600, 290, 1, 0, 0),
        (88, 'halflife', 'firearms', 'ps_upham', -930, -3930, 3890, 3705, 600, 379, 1, 0, 0),
        (89, 'halflife', 'firearms', 'sd_durandal', -2820, -3965, 3980, 1255, 600, 459, 1, 0, 0),
        (90, 'halflife', 'firearms', 'sd_force', -3555, -3575, 3450, 2425, 600, 513, 1, 0, 0),
        (91, 'halflife', 'firearms', 'sd_oberland', -2425, -3880, 3245, 3335, 466, 600, 1, 0, 0),
        (92, 'halflife', 'firearms', 'sdtc_balcome', -1395, -3710, 2560, 3775, 600, 319, 1, 0, 0),
        (93, 'halflife', 'firearms', 'tc_basrah', -2865, -2290, 3305, 2270, 600, 444, 1, 0, 0),
        (94, 'halflife', 'firearms', 'tc_caen', -3070, -3805, 2555, 3960, 600, 435, 1, 0, 0),
        (95, 'halflife', 'firearms', 'tc_golan', -3520, -3925, 3940, 3705, 600, 585, 1, 0, 0),
        (96, 'halflife', 'firearms', 'tc_iwojima', -3180, -1140, 1975, 1705, 600, 326, 1, 0, 0),
        (97, 'halflife', 'firearms', 'tc_okinawa_b4', -1915, -3960, 1735, 4000, 600, 275, 1, 0, 0),
        (98, 'halflife', 'firearms', 'tc_rubble', -1070, -890, 2560, 1655, 600, 428, 1, 0, 0),
        (99, 'halflife', 'firearms', 'tc_thebes', -3935, -3505, 3885, 3430, 600, 532, 1, 0, 0);

-- QoL.
INSERT INTO `ps_weapon` (`weaponid`, `uniqueid`, `name`, `skillweight`, `class`) 
    VALUES 
        (1, 'uzi', 'UZI Submachine Gun', 1.58, 'Submachine Gun'),
        (2, 'm16', 'M16 Rifle', 1.15, 'Rifle'),
        (3, 'm249', 'M249 Light Machine Gun', 1.35, 'Machine Gun'),
        (4, 'bizon', 'Bizon', 1.58, 'Submachine Gun'),
        (5, 'bleed', 'Bled to Death', 3.13, 'Wounds'),
        (6, 'mp5a5', 'Heckler & Koch MP5A5', 1.50, 'Submachine Gun'),
        (7, 'm4', 'M4 Carbine', 1.18, 'Assault Rifle'),
        (8, 'remington', 'Remington Shotgun', 1.80, 'Shotgun'),
        (9, 'ak47', 'AK-47', 1.00, 'Assault Rifle'),
        (10, 'ak74', 'AK-74', 1.15, 'Assault Rifle'),
        (11, 'svd', 'Dragunov Sniper Rifle', 1.65, 'Sniper Rifle'),
        (12, 'g36e', 'Gewehr 36E', 1.08, 'Assault Rifle'),
        (13, 'ssg3000', 'SIG Sauer SSG 3000', 1.70, 'Sniper Rifle'),
        (14, 'm14', 'M14 Rifle', 1.08, 'Rifle'),
        (15, 'ber93r', 'Beretta 93R', 1.95, 'Hand Gun'),
        (16, 'm60', 'M60 Machine Gun', 1.45, 'Machine Gun'),
        (17, 'coltgov', 'Colt Government', 1.80, 'Hand Gun'),
        (18, 'frag', 'Fragmentation Grenade', 2.88, 'Grenade'),
        (19, 'ber92f', 'Beretta 92F', 1.95, 'Hand Gun'),
        (20, 'anaconda', 'Anaconda', 2.03, 'Hand Gun'),
        (21, 'saiga', 'Saiga Shotgun', 1.75, 'Shotgun'),
        (22, 'famas', 'FAMAS', 1.00, 'Assault Rifle'),
        (23, 'm79', 'M79 Grenade Launcher', 2.13, 'Grenade Launcher'),
        (24, 'bayonet', 'AK-47 Bayonet', 3.00, 'Melee'),
        (25, 'sterling', 'Sterling Submachine Gun', 1.63, 'Submachine Gun'),
        (26, 'desert', 'Desert Eagle', 1.80, 'Hand Gun'),
        (27, 'knife', 'Combat Knife', 2.25, 'Melee'),
        (28, 'pkm', 'PK Machine Gun', 1.33, 'Machine Gun'),
        (29, 'm82', 'Barrett M82', 1.75, 'Sniper Rifle'),
        (30, 'claymore', 'Claymore Mine', 1.32, 'Antipersonnel Mine'),
        (31, 'g3a3', 'Gewehr 3A3', 1.00, 'Assault Rifle'),
        (32, 'ammobox', 'Exploding Ammunition Crate', 3.25, 'World'),
        (33, 'gp25', 'GP-25 Kostyor', 2.70, 'Grenade Launcher'),
        (34, 'm203', 'M203 Grenade Launcher', 2.70, 'Grenade Launcher');
